spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        #  最大数据库连接数
        max-active: 8
        #  最大等待连接数
        max-idle: 8
        #  最大等待连接时间，过期超时 -1无限制
        max-wait: 1000
        #  最小等待连接时间 0无限制
        min-idle: 0
      shutdown-timeout: 1000



provider:
  namesrvAddress: 127.0.0.1:9876
